### ISSUE TITLE
Updating custom group should use data in dgraph

### ISSUE THREAD

**Issue by kreddyj** [vmware/purser#124]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind feature

**What happened**:
Now, whenever there is an event related to pod we update the custom groups. This causes too many calls to Kubernetes api server.

**What you expected to happen**:
We should utilize the data stored in dgraph. Once in every few minutes we can update custom group's spec using data from dgraph.

**Tasks**:

- [x]  Store labels of pods in dgraph
- [x] Write a query to retrieve all pods of particular label(key:value) from dgraph
- [x] A cronjob that updates spec of custom group every few minutes
- [x] Update code in plugin side to handle the above changes.
