### ISSUE TITLE
Store nodes and volumes prices for AWS

### ISSUE THREAD

**Issue by kreddyj** [vmware/purser#145]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened and What you expected to happen**:
For providing accurate costs as mentioned in [Pricing in Purser](https://github.com/vmware/purser/blob/master/docs/design/pricing.md) documentation we need to have prices of compute instances and storage for AWS cloud provider.

**Tasks**:
- [x]  Retrieve and filter price list from AWS
- [x]  Store the rate card in dgraph
- [ ]  Periodically update the rate card
