### ISSUE TITLE
 Store nodes and volumes prices for Google Kubernetes Engine

### ISSUE THREAD

**Issue by kreddyj** [vmware/purser#148]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened and What you expected to happen**:
For providing accurate costs as mentioned in [Pricing in Purser](https://github.com/vmware/purser/blob/master/docs/design/pricing.md) documentation we need to have prices of compute instances and storage for [GKE](https://cloud.google.com/kubernetes/) cloud provider.

**Tasks**:
- [ ]  Retrieve and filter price list from GKE
- [ ]  Store the rate card in dgraph
- [ ]  Periodically update the rate card
